export const FETCH_DATA_FROM_API_SUCCESS = 'FETCH_DATA_FROM_API_SUCCESS';
export const FETCH_DATA_FROM_API_FAIL = 'FETCH_DATA_FROM_API_FAIL';
export const FETCH_DATA_RECOMMENDED_SUCCESS = 'FETCH_DATA_RECOMMENDED_SUCCESS';
